export default class CommonContent {

/*
组件尺寸定义
 */
  static readonly FULL_WIDTH = '100%';
  static readonly FULL_HEIGHT = '100%';
  static readonly HALF_SIZE = '50%';
  static readonly CONTENT_SIZE = '100%';
  static readonly FONT_BOLDER = '700'
  static readonly INPUT_PADDING_LEFT = 0;
  static readonly LOGIN_DELAY_TIME = 2000;
  static readonly COMMON_SPACE = 12;
  /**
   * Title text of the home page
   */
  static readonly HOME_TITLE = '首页';

  /**
   * Title text of the setting page
   */
  static readonly MINE_TITLE = '我的';

  /**
   * Spacing of other login methods
   */
  static readonly LOGIN_METHODS_SPACE = 44;

  /**
   * The width or height of the component is spread across the parent component.
   */
  static readonly FULL_PARENT = '100%';

  /**
   * The width of button
   */
  static readonly BUTTON_WIDTH = '90%';

  /**
   * Home tab index
   */
  static readonly HOME_TAB_INDEX = 0;

  /**
   * Mine tab index
   */
  static readonly MINE_TAB_INDEX = 1;
}